### ISSUE TITLE
Pensar un nuevo título

### ISSUE THREAD

**Issue by fergunet** [geneura-papers/2015-ASOCO#8]
Uno de los revisores dice: _5. The title of this paper is not quite appropriate because the offline parameter settings (parameter tuning) is not called "adaptation"._

He pensado cambiarlo por "A study on population size effect in distributed evolutionary algorithms on heterogeneous clusters". ¿Os parece bien este título?

**Comment by JJ** [comment]
"on the effect of the population size"

2015-01-27 11:14 GMT+01:00 Pablo García Sánchez notifications@github.com:

> Uno de los revisores dice: _5. The title of this paper is not quite
> appropriate because the offline parameter settings (parameter tuning) is
> not called "adaptation"._
> 
> He pensado cambiarlo por "A study on population size effect in distributed
> evolutionary algorithms on heterogeneous clusters". ¿Os parece bien este
> título?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/geneura-papers/2015-ASOCO/issues/8.

## 

JJ

**Comment by amorag** [comment]
Nunca me han gustado los trabajos con el prefijo o coletilla ‘A study’, aunque yo mismo los tenga.

Deja entrever que es una cosa puntual y que puede ser poco relevante, excepto en casos muy específicos. ;)

Yo lo titularía:

“Effect of the population size in distributed evolutionary algorithms on heterogeneous clusters”

¡Taluego!

De: Pablo García Sánchez [mailto:notifications@github.com] 
Enviado el: martes, 27 de enero de 2015 11:15
Para: geneura-papers/2015-ASOCO
Asunto: [2015-ASOCO] Pensar un nuevo título (#8)

Uno de los revisores dice: 5. The title of this paper is not quite appropriate because the offline parameter settings (parameter tuning) is not called "adaptation".

He pensado cambiarlo por "A study on population size effect in distributed evolutionary algorithms on heterogeneous clusters". ¿Os parece bien este título?

—
Reply to this email directly or view it on GitHub https://github.com/geneura-papers/2015-ASOCO/issues/8 .  https://github.com/notifications/beacon/AC6-WtxlJIIp7U6CeeAVX2OmvUZx4588ks5nl1yegaJpZM4DXq5k.gif 

No se encontraron virus en este mensaje.
Comprobado por AVG - www.avg.com
Versión: 2015.0.5645 / Base de datos de virus: 4273/9007 - Fecha de publicación: 01/27/15

**Comment by mgarenas** [comment]
Yo metería algo de adaptación de los tamaños de población al hardware de 
ejecución, para destacar qué es lo que tú propones. Lo que propones es 
un mejor aprovechamiento del hardware adaptando las poblaciones y se 
supone que será mejor que no adaptarlas, por lo que intentaría reflejar 
en el título esa característica de tu trabajo, incluso aunque el tamaño 
de población se haga offline.

Maribel

**Comment by mgarenas** [comment]
“Effect of the population size in distributed evolutionary algorithms on 
heterogeneous clusters”

Este lo veo también descriptivo. Lo de "A study..." también me da la 
sensación de que es algo muy puntual.

Maribel
